project_id = "wumicfakfvhkktscdxzt"

[functions.create-user]
verify_jwt = false

[functions.setup-superadmin]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.setup-demo]
verify_jwt = false